### Listar Empleado

GET http://localhost:3000/empleado

### Registrar Empleado
POST http://localhost:3000/empleado
Content-Type: application/json

{
  "nombre": "Pedro",
  "apellido": "Jimenez",
  "telefono": "0991234565",
  "cedula": "1723456785",
  "correo": "pedro@gmail.com",
  "salario": 230,
  "id_cargo": 2,
  "id_departamento": 2
}


### Mostrar Empleado
GET http://localhost:3000/empleado/5

### Actualizar Empleado
PUT http://localhost:3000/empleado/5
Content-Type: application/json

{
  "nombre": "Pedro",
  "apellido": "Herrera",
  "telefono": "0991234568",
  "cedula": "1723456785",
  "correo": "pedro@gmail.com",
  "salario": 2000.00,
  "id_cargo": 4,
  "id_departamento": 1
}


### Eliminar Empleado
DELETE http://localhost:3000/empleado/4              